CONFIG_OPENAMP=y
CONFIG_HEAP_MEM_POOL_SIZE=131072

CONFIG_PCIE=y
CONFIG_PCIE_CONTROLLER=y
CONFIG_PCIE_ECAM=y
CONFIG_POLL=y
CONFIG_DYNAMIC_INTERRUPTS=y

CONFIG_VIRTUALIZATION=y
CONFIG_IVSHMEM_V2=y
CONFIG_IVSHMEM_DOORBELL=y
