#!/usr/bin/env python3
# Copyright (c) 2026 MediaTek Inc.
# SPDX-License-Identifier: Apache-2.0
"""Generate bench_coeffs.h: the fixed-point filters of the eTDM latency bench.

Both are low-pass at FC_HZ for a 48 kHz stream, so a filtered channel that is
fed back around the loop decays instead of growing:

  FIR  FIR_TAPS taps, Hamming-windowed sinc, Q31, scaled to a DC gain of
       FIR_DC_GAIN.
  IIR  8th-order Butterworth as four biquads (RBJ low-pass sections with the
       Butterworth pole Qs), coefficients in Q2.30, each section unity DC gain
       and IIR_GAIN applied to the input of the first.

Rerun after changing a parameter; the header is checked in so the targets do
not need Python to build.
"""
import math
import os

import numpy as np

RATE = 48000
FC_HZ = 8000
FIR_TAPS = 64
FIR_DC_GAIN = 0.9
IIR_SECTIONS = 4
IIR_GAIN = 0.9

Q31 = 1 << 31
Q30 = 1 << 30


def q(x, one):
    v = int(round(x * one))
    return max(-(1 << 31), min((1 << 31) - 1, v))


def fir_coeffs():
    n = np.arange(FIR_TAPS) - (FIR_TAPS - 1) / 2
    h = 2 * FC_HZ / RATE * np.sinc(2 * FC_HZ / RATE * n) * np.hamming(FIR_TAPS)
    h *= FIR_DC_GAIN / h.sum()
    return [q(c, Q31) for c in h]


def iir_coeffs():
    order = 2 * IIR_SECTIONS
    w0 = 2 * math.pi * FC_HZ / RATE
    sections = []
    for k in range(IIR_SECTIONS):
        theta = math.pi * (2 * k + 1) / (2 * order)
        qf = 1 / (2 * math.cos(theta))
        alpha = math.sin(w0) / (2 * qf)
        a0 = 1 + alpha
        b0 = (1 - math.cos(w0)) / 2 / a0
        b1 = (1 - math.cos(w0)) / a0
        b2 = b0
        a1 = -2 * math.cos(w0) / a0
        a2 = (1 - alpha) / a0
        sections.append([q(c, Q30) for c in (b0, b1, b2, a1, a2)])
    return sections


def main():
    fir = fir_coeffs()
    iir = iir_coeffs()
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'bench_coeffs.h')
    with open(out, 'w') as f:
        f.write('/*\n * Copyright (c) 2026 MediaTek Inc.\n *\n'
                ' * SPDX-License-Identifier: Apache-2.0\n *\n'
                ' * Generated by gen_coeffs.py -- do not edit.\n'
                f' * Low-pass at {FC_HZ} Hz for {RATE} Hz streams.\n */\n\n')
        f.write('#ifndef BENCH_COEFFS_H_\n#define BENCH_COEFFS_H_\n\n#include <stdint.h>\n\n')
        f.write(f'/* {FIR_TAPS}-tap Hamming-windowed sinc, Q31, DC gain {FIR_DC_GAIN}. */\n')
        f.write(f'#define BENCH_FIR_TAPS {FIR_TAPS}\n\n')
        f.write('static const int32_t bench_fir_coeffs[BENCH_FIR_TAPS] = {\n')
        for i in range(0, FIR_TAPS, 4):
            f.write('\t' + ', '.join(f'{c:11d}' for c in fir[i:i + 4]) + ',\n')
        f.write('};\n\n')
        f.write(f'/* 8th-order Butterworth as {IIR_SECTIONS} biquads, Q2.30: b0 b1 b2 a1 a2. */\n')
        f.write(f'#define BENCH_IIR_SECTIONS {IIR_SECTIONS}\n')
        f.write(f'#define BENCH_IIR_GAIN_Q31 {q(IIR_GAIN, Q31)}\n\n')
        f.write('static const int32_t bench_iir_coeffs[BENCH_IIR_SECTIONS][5] = {\n')
        for s in iir:
            f.write('\t{ ' + ', '.join(f'{c:11d}' for c in s) + ' },\n')
        f.write('};\n\n#endif /* BENCH_COEFFS_H_ */\n')


if __name__ == '__main__':
    main()
